accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (
    register_user,
    MyOrderListView,
    ProfileView,
    MyOrderDetailView,
    UserListView, UserDetailView, SupportCreateView, AccountUpdateView
)

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'),
         name='login'),
    path('register/', register_user,
         name='register'),
    path('logout/', LogoutView.as_view(),
         name='logout'),

    path('myorders/', MyOrderListView.as_view(),
         name='myorder-list'),
    path('myorders/<int:pk>/', MyOrderDetailView.as_view(),
         name='myorder-detail'),

    path('profile/', ProfileView.as_view(),
         name='profile'),
    path('users/', UserListView.as_view(),
         name='user-list'),
    path('users/<int:pk>/', UserDetailView.as_view(),
         name='user-detail'),
    path('account/', AccountUpdateView.as_view(),
         name='account-update'),

    path('support/', SupportCreateView.as_view(),
         name='support'),
]

app_name = "accounts"

minishop_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shop.urls", namespace="shop")),
    path("accounts/", include(("accounts.urls", "accounts"), namespace="accounts")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path

from .views import (
    index,
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    OrderListView,
    ProductCategoryListView,
    ProductCategoryDetailView,
    ProductCategoryCreateView,
    ProductCategoryUpdateView,
    ProductCategoryDeleteView,
    add_to_cart,
    cart_detail,
    confirm_order,
    update_cart,
    remove_from_cart,
    OrderDetailView
)

urlpatterns = [
    path('', index, name='index'),
    path('products/', ProductListView.as_view(),
         name='product-list'),
    path('products/<int:pk>/', ProductDetailView.as_view(),
         name='product-detail'),
    path('products/create/', ProductCreateView.as_view(),
         name='product-create'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(),
         name='product-update'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(),
         name='product-delete'),

    path('orders/', OrderListView.as_view(),
         name='order-list'),
    path('orders/<int:pk>/', OrderDetailView.as_view(),
         name='order-detail'),

    path('categories/', ProductCategoryListView.as_view(),
         name='productcategory-list'),
    path('categories/create/', ProductCategoryCreateView.as_view(),
         name='productcategory-create'),
    path('categories/<int:pk>/', ProductCategoryDetailView.as_view(),
         name='productcategory-detail'),
    path('categories/<int:pk>/update/', ProductCategoryUpdateView.as_view(),
         name='productcategory-update'),
    path('categories/<int:pk>/delete/', ProductCategoryDeleteView.as_view(),
         name='productcategory-delete'),

    path("cart/add/<int:pk>/", add_to_cart,
         name="add-to-cart"),
    path("cart/", cart_detail,
         name="cart-detail"),
    path("order/confirm/", confirm_order,
         name="order-confirm"),
    path("cart/update/<int:pk>/", update_cart,
         name="cart-update"),
    path("cart/remove/<int:pk>/", remove_from_cart,
         name="cart-remove"),
]

app_name = "shop"

accounts/models.py
from django.conf import settings
from django.db import models


class SupportRequest(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_processed = models.BooleanField(default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.title} ({self.created_at:%Y-%m-%d %H:%M})"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from accounts.models import SupportRequest

User = get_user_model()

class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Email",
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password check",
                "class": "form-control"
            }
        ))
    first_name = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            "placeholder": "First Name",
            "class": "form-control"
        })
    )

    last_name = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            "placeholder": "Last Name",
            "class": "form-control"
        })
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name')


class SupportRequestForm(forms.ModelForm):
    class Meta:
        model = SupportRequest
        fields = ('title', 'content')
        widgets = {
            'title': forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "Title",
            }),
            'content': forms.Textarea(attrs={
                "class": "form-control",
                "rows": 4,
                "placeholder": "Content",
            }),
        }


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name')

        widgets = {
            'email': forms.EmailInput(attrs={
                "placeholder": "Email",
                "class": "form-control"
            }),
            'first_name': forms.TextInput(attrs={
                "placeholder": "First Name",
                "class": "form-control"
            }),
            'last_name': forms.TextInput(attrs={
                "placeholder": "Last Name",
                "class": "form-control"
            }),
        }

accounts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from shop.mixins import OrderFilterMixin, BackUrlDetailMixin
from shop.models import Order
from .forms import SignUpForm, SupportRequestForm, UserUpdateForm
from django.contrib.auth import get_user_model

from .models import SupportRequest

User = get_user_model()


def register_user(request):
    msg = None
    success = False

    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            # username = form.cleaned_data.get("username")
            # raw_password = form.cleaned_data.get("password1")
            # user = User.objects.create_user(username=username, password=raw_password)

            msg = 'Account created successfully.'
            success = True

            messages.success(request, "Account created successfully.")
            return redirect("accounts:login")

        else:
            msg = 'Form is not valid'
    else:
        form = SignUpForm()

    return render(request, "accounts/register.html", {"form": form, "msg": msg, "success": success})


class UserListView(LoginRequiredMixin, UserPassesTestMixin, generic.ListView):
    model = User
    context_object_name = "user_list"
    template_name = "accounts/user_list.html"
    paginate_by = 10

    def test_func(self):
        return self.request.user.is_staff or self.request.user.is_employee


class UserDetailView(LoginRequiredMixin, UserPassesTestMixin, BackUrlDetailMixin, generic.DetailView):
    model = User
    template_name = "accounts/user_detail.html"
    context_object_name = "user_detail"

    def test_func(self):
        return self.request.user.is_staff or self.request.user.is_employee


class AccountUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = "accounts/account_update.html"
    success_url = reverse_lazy("accounts:profile")

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request, "The changes were saved successfully.")
        return super().form_valid(form)


class MyOrderListView(LoginRequiredMixin, OrderFilterMixin, generic.ListView):
    model = Order
    paginate_by = 10
    template_name = "accounts/myorder_list.html"
    context_object_name = "myorder_list"
    ordering = ["-created_at"]

    def get_base_queryset(self):
        return super().get_base_queryset().filter(user=self.request.user).order_by("-created_at")

class MyOrderDetailView(LoginRequiredMixin, BackUrlDetailMixin, generic.DetailView):
    model = Order
    paginate_by = 20
    template_name = "accounts/myorder_detail.html"

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user).prefetch_related("items__product")


class ProfileView(LoginRequiredMixin, generic.TemplateView):
    template_name = "accounts/profile.html"


class SupportCreateView(generic.CreateView):
    model = SupportRequest
    form_class = SupportRequestForm
    template_name = "accounts/support_form.html"
    success_url = reverse_lazy("shop:index")

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.user = self.request.user

        messages.success(self.request, "The message was sent successfully.")

        return super().form_valid(form)

templates/accounts/account_update.html
{% extends 'layouts/base-fullscreen.html' %}

{% block content %}

  {% include "includes/navigation-auth.html" %}
  
  <section>
    <div class="page-header section-height-100">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
            <div class="card card-plain">
              <div class="card-header pb-0 text-left">
                <h4 class="font-weight-bolder">My account</h4>
              </div>
              <div class="card-body">
                <form method="post" novalidate>
                  {% csrf_token %}

                  <div class="mb-3">
                    {{ form.email }}
                  </div>
                  <span class="text-error">{{ form.email.errors }}</span>

                  <div class="mb-3">
                    {{ form.first_name }}
                  </div>
                  <span class="text-error">{{ form.first_name.errors }}</span>

                  <div class="mb-3">
                    {{ form.last_name }}
                  </div>
                  <span class="text-error">{{ form.last_name.errors }}</span>

                  <div class="text-center">
                    <button type="submit"
                            class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Save changes</button>
                  </div>

                  <div class="text-center">
                    <a href="{% url 'shop:index' %}" class="btn btn-lg bg-gradient-secondary btn-lg w-100 mt-4 mb-0">Cancel</a>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

templates/accounts/login.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Sign IN {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} sign-in-illustration {% endblock body_class %}

{% block content %}

  {% include "includes/navigation-auth.html" %}

  <section>
    <div class="page-header section-height-100">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
            <div class="card card-plain">
              <div class="card-header pb-0 text-left">
                {% if messages %}
                  {% for message in messages %}
                    <div class="alert alert-success">{{ message }}</div>
                  {% endfor %}
                {% endif %}
                <h4 class="font-weight-bolder">Sign In</h4>
                <p class="mb-0">
                  {% if msg %}
                      {{ msg | safe }}
                  {% else %}
                      Add your credentials
                  {% endif %}
                </p>
              </div>
              <div class="card-body">

                <form method="post" action="{% url 'accounts:login' %}" role="form">

                  {% csrf_token %}

                  <div class="mb-3">
                    {{ form.username }}
                  </div>
                  <div class="mb-3">
                    {{ form.password }}
                  </div>
                  <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="rememberMe">
                    <label class="form-check-label" for="rememberMe">Remember me</label>
                  </div>
                  <div class="text-center">
                    <button type="submit" name="login"
                            class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Sign in</button>
                  </div>
                  {% if form.errors %}
                    <div class="alert alert-danger">
                      {{ form.non_field_errors }}
                      {{ form.username.errors }}
                      {{ form.password.errors }}
                    </div>
                  {% endif %}
                </form>
              </div>
              <div class="card-footer text-center pt-0 px-lg-2 px-1">
                <p class="mb-4 text-sm mx-auto">
                  Don't have an account?
                  <a href="{% url 'accounts:register' %}" class="text-primary text-gradient font-weight-bold">Sign UP</a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>

{% endblock javascripts %}

templates/accounts/myorder_detail.html
{% extends "layouts/base-presentation.html" %}
{#{% load crispy_forms_filters %}#}

{% block content %}
  <div class="container mt-sm-5">
    <div class="page-header section-height-50 my-sm-3 mb-3 border-radius-xl" style="background-image: url('https://unsplash.com/photos/IVj7aVIi0zM/download?ixid=M3wxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNzQ1NTIyMzY0fA&force=true');">
      <span class="mask bg-gradient-dark"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-6 ms-lg-5">
            <h1 class="text-white">Order #{{ object.id }}</h1>
            <p class="lead text-white"> {{ object.created_at }} </p>
            <p class="lead text-white"> {{ object.status }} </p>
            <h4 class="text-end">
              <a href="{% url 'accounts:myorder-list' %}" class="btn btn-outline-light btn-sm mb-3">
                Go to orders
              </a>
              <a href="{{ back_url|default:'/' }}" class="btn btn-outline-light btn-sm mb-3">
                Back
                <i class="fas fa-arrow-right text-sm ms-1"></i>
              </a>
            </h4>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="column">
      {% for item in object.items.all %}
        <div class="col-lg-4 col-md-4 col-sm-6 mb-4">
          <div class="info-horizontal border-radius-xl p-5" style="background: linear-gradient(135deg, #4a6fa5, #d3d3d3); color: black;">
            <div class="description ps-5">
              <h5 class="text-white">{{ item.product.name }}</h5>
              <p class="text-sm">Quantity: {{ item.quantity }}</p>
              <p class="text-sm">Price per piece: {{ item.product.price }}</p>
              <p class="text-sm">Price: {{ item.get_total_price }}</p>
            </div>
          </div>
        </div>
      {% empty %}
        <p class="text-center">No orders found.</p>
      {% endfor %}

      <hr>
      <h4 class="text-end">
        Total: {{ object.get_total_price }}
      </h4>
    </div>
  </div>
{% endblock %}

templates/accounts/myorder_list.html
{% extends "layouts/base-presentation.html" %}
{#{% load crispy_forms_filters %}#}

{% block content %}
  <div class="container mt-sm-5">
    <div class="page-header section-height-50 my-sm-3 mb-3 border-radius-xl" style="background-image: url('https://unsplash.com/photos/IVj7aVIi0zM/download?ixid=M3wxMjA3fDB8MXxhbGx8fHx8fHx8fHwxNzQ1NTIyMzY0fA&force=true');">
      <span class="mask bg-gradient-dark"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-6 ms-lg-5">
            <h1 class="text-white">My orders</h1>
            <p class="lead text-white opacity-8">Customer orders and their current processing status.</p>
          </div>
        </div>
      </div>
    </div>
    <h5 class="mb-3">Filter orders</h5>
    <form method="get" class="row g-2 mb-4" >
      <div class="col-md-2">
        {{  filter_form.name }}
      </div>
      <div class="col-md-1">
        {{  filter_form.status  }}
      </div>
      <div class="col-md-1">
        {{  filter_form.total_min  }}
      </div>
      <div class="col-md-1">
        {{  filter_form.total_max  }}
      </div>
      <div class="col-md-2">
        {{  filter_form.date_from  }}
      </div>
      <div class="col-md-2">
        {{  filter_form.date_to  }}
      </div>
      <div class="col-md-1">
        <button class="btn bg-gradient-primary">
          🔎
        </button>
      </div>
      <div class="col-md-1">
        <a href="{% url 'accounts:myorder-list' %}" class="btn bg-gradient-primary">
          Reset
        </a>
      </div>
    </form>
  </div>

  <div class="container">
    <div class="row">
      {% for order in myorder_list %}
        <div class="col-lg-4 col-md-4 col-sm-6 mb-4">
          <a href="{% url 'accounts:myorder-detail' pk=order.id%}" class="text-decoration-none">
            <div class="info-horizontal border-radius-xl p-5" style="background: linear-gradient(135deg, #4a6fa5, #d3d3d3); color: black;">
              <div class="icon">
                <svg class="text-white" width="25px" height="25px" viewBox="0 0 46 43" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                  <title>delivery-fast</title>
                </svg>
              </div>
              <div class="description ps-5">
                <h5 class="text-white">Order: {{ order.id }}</h5>
                <p class="text-sm">Status: {{ order.status }}</p>
                <p class="text-sm">Created: {{ order.created_at|date:"Y-m-d H:i" }}</p>
                <p class="text-sm">Price: {{ order.get_total_price }}</p>
              </div>
            </div>
          </a>
        </div>
      {% empty %}
        <p class="text-center">No orders found.</p>
      {% endfor %}
      <a href="{% url 'shop:product-list' %}" class="btn btn-primary mt-4">
        Create new order
      </a>
    </div>
  </div>
{% endblock %}

templates/accounts/profile.html
{% extends "layouts/base-presentation.html" %}
{#{% load crispy_forms_filters %}#}

{% block content %}
  <div class="container mt-sm-5">
    <div class="page-header section-height-50 my-sm-3 mb-3 border-radius-xl"
         style="background-image: url('https://unsplash.com/photos/IVj7aVIi0zM/download?force=true');">
      <span class="mask bg-gradient-dark"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-6 ms-lg-5">
            <h1 class="text-white">My Account</h1>
            <p class="lead text-white opacity-8">
              Personal information and account status
            </p>
            {% if user.is_authenticated %}
              <a href="{% url 'accounts:account-update' %}" class="btn bg-gradient-primary">Change info</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row justify-content-center">

      <div class="col-lg-6 col-md-8">
        <div class="card shadow-lg border-radius-xl">

          <div class="card-body p-4">

            <p class="mb-2">
              <strong>Username:</strong>
              {{ request.user.username }}
            </p>

            <p class="mb-2">
              <strong>Full name:</strong>
              {{ request.user.get_full_name|default:"None" }}
            </p>

            <p class="mb-4">
              <strong>Email:</strong>
              {{ request.user.email|default:"None" }}
            </p>

            <hr>

            {% if request.user.is_staff or request.user.is_employee %}
              <span class="badge bg-gradient-info">Staff</span>
            {% else %}
              <span class="badge bg-gradient-success">Customer</span>
            {% endif %}

          </div>

        </div>
      </div>

    </div>
  </div>
{% endblock %}

templates/accounts/register.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Sign UP {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} sign-in-illustration {% endblock body_class %}

{% block content %}

  {% include "includes/navigation-auth.html" %}
  
  <section>
    <div class="page-header section-height-100">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
            <div class="card card-plain mt-5">
              <div class="card-header pb-0 text-left">
                <h4 class="font-weight-bolder">Sign UP</h4>
                <p class="mb-0">
                  {% if msg %}
                      {{ msg | safe }}
                  {% else %}
                      Add your credentials
                  {% endif %}                
                </p>
              </div>
              <div class="card-body">
                <form method="post" action="" role="form">

                  {% csrf_token %}
                  
                  <div class="mb-3">
                    {{ form.username }}
                  </div>                
                  <span class="text-error">{{ form.username.errors }}</span>

                  <div class="mb-3">
                    {{ form.email }}
                  </div>
                  <span class="text-error">{{ form.email.errors }}</span>
                  
                  <div class="mb-3">
                    {{ form.password1 }}
                  </div>
                  <span class="text-error">{{ form.password1.errors }}</span>

                  <div class="mb-3">
                    {{ form.password2 }}
                  </div>
                  <span class="text-error">{{ form.password2.errors }}</span>

                  <div class="mb-3">
                    {{ form.first_name }}
                  </div>
                  <span class="text-error">{{ form.first_name.errors }}</span>

                  <div class="mb-3">
                    {{ form.last_name }}
                  </div>
                  <span class="text-error">{{ form.last_name.errors }}</span>

                  <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="rememberMe">
                    <label class="form-check-label" for="rememberMe">
                      Agree with <a href="#">terms</a>
                    </label>
                  </div>
                  <div class="text-center">
                    <button type="submit" name="register"
                            class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Register</button>
                  </div>
                </form>
              </div>
              <div class="card-footer text-center pt-0 px-lg-2 px-1">
                <p class="mb-4 text-sm mx-auto">
                  Have an account?
                  <a href="{% url 'accounts:login' %}" class="text-primary text-gradient font-weight-bold">Sign IN</a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>

{% endblock javascripts %}

templates/accounts/support_form.html
{% extends 'layouts/base-fullscreen.html' %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center" style="background: linear-gradient(135deg, #4a6fa5, #d3d3d3); color: black;">
      <div class="col-md-5">
        <h3 class="text-center">
            Support
        </h3>

        <form method="post" novalidate>
          {% csrf_token %}
          <div class="mb-3">
            {{ form.title }}
          </div>
          <div class="mb-3">
            {{ form.content }}
          </div>
          <button type="submit" class="btn bg-gradient-primary w-100">
            Send
          </button>
        </form>
      </div>
      <div class="mt-4">
        {% if user.is_authenticated %}
          <a href="{% url 'shop:index' %}" class="btn bg-gradient-secondary">Back to shop</a>
        {% else %}
          <a href="{% url 'accounts:login' %}" class="btn bg-gradient-secondary">Login</a>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

templates/accounts/user_detail.html
{% extends "layouts/base-presentation.html" %}
{#{% load crispy_forms_filters %}#}

{% block content %}
  <div class="container mt-sm-5">
    <div class="page-header section-height-50 my-sm-3 mb-3 border-radius-xl"
         style="background-image: url('https://unsplash.com/photos/IVj7aVIi0zM/download?force=true');">
      <span class="mask bg-gradient-dark"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-6 ms-lg-5">
            <h1 class="text-white">User profile</h1>
            <p class="lead text-white opacity-8">
              Personal information and account status
            </p>
            <h4 class="text-end">
              <a href="{{ back_url|default:'/' }}" class="btn btn-outline-light btn-sm mb-3">
                Back
              </a>
            </h4>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row justify-content-center">

      <div class="col-lg-6 col-md-8">
        <div class="card shadow-lg border-radius-xl">

          <div class="card-body p-4">

            <p class="mb-2">
              <strong>Username:</strong>
              {{ user_detail.username }}
            </p>

            <p class="mb-2">
              <strong>Full name:</strong>
              {{ user_detail.get_full_name|default:"None" }}
            </p>

            <p class="mb-4">
              <strong>Email:</strong>
              {{ user_detail.email|default:"None" }}
            </p>

            <hr>

            {% if user_detail.is_staff or user_detail.is_employee %}
              <span class="badge bg-gradient-info">Staff</span>
            {% else %}
              <span class="badge bg-gradient-success">Customer</span>
            {% endif %}

            <hr>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/accounts/user_list.html
{% extends "layouts/base-presentation.html" %}
{#{% load crispy_forms_filters %}#}

{% block content %}
  <div class="container mt-sm-5">
    <div class="page-header section-height-50 my-sm-3 mb-3 border-radius-xl" style="background-image: url('https://unsplash.com/photos/h3JLBMq7haM/download?ixid=M3wxMjA3fDB8MXxzZWFyY2h8Mnx8Y29va3N8ZW58MHx8fHwxNzQ1NTMyNzEzfDA&force=true');">
      <span class="mask bg-gradient-dark"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-6 ms-lg-5">
            <h1 class="text-white">Users</h1>
            <p class="lead text-white opacity-8">View and manage users.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      {% for user in user_list %}
        <div class="col-lg-4 col-md-4 col-sm-6 mb-4">
          <a href="{% url 'accounts:user-detail' pk=user.id%}" class="text-decoration-none">
            <div class="info-horizontal border-radius-xl p-5" style="background: linear-gradient(135deg, #4a6fa5, #d3d3d3); color: black;">
              <div class="description ps-5">
                <h5 class="text-white">{{ user.username }}</h5>
                <p class="text-white">Last login: {{ user.last_login }}</p>
              </div>
            </div>
          </a>
        </div>
      {% empty %}
        <p class="text-center">No users found.</p>
      {% endfor %}
    </div>
  </div>
{% endblock %}