minishop_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shop.urls", namespace="shop")),
    path("accounts/", include(("accounts.urls", "accounts"), namespace="accounts")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path

from .views import (
    index,
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    OrderListView,
    ProductCategoryListView,
    ProductCategoryDetailView,
    ProductCategoryCreateView,
    ProductCategoryUpdateView,
    ProductCategoryDeleteView,
    add_to_cart,
    cart_detail,
    confirm_order,
    update_cart,
    remove_from_cart,
    OrderDetailView
)

urlpatterns = [
    path('', index, name='index'),
    path('products/', ProductListView.as_view(),
         name='product-list'),
    path('products/<int:pk>/', ProductDetailView.as_view(),
         name='product-detail'),
    path('products/create/', ProductCreateView.as_view(),
         name='product-create'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(),
         name='product-update'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(),
         name='product-delete'),

    path('orders/', OrderListView.as_view(),
         name='order-list'),
    path('orders/<int:pk>/', OrderDetailView.as_view(),
         name='order-detail'),

    path('categories/', ProductCategoryListView.as_view(),
         name='productcategory-list'),
    path('categories/create/', ProductCategoryCreateView.as_view(),
         name='productcategory-create'),
    path('categories/<int:pk>/', ProductCategoryDetailView.as_view(),
         name='productcategory-detail'),
    path('categories/<int:pk>/update/', ProductCategoryUpdateView.as_view(),
         name='productcategory-update'),
    path('categories/<int:pk>/delete/', ProductCategoryDeleteView.as_view(),
         name='productcategory-delete'),

    path("cart/add/<int:pk>/", add_to_cart,
         name="add-to-cart"),
    path("cart/", cart_detail,
         name="cart-detail"),
    path("order/confirm/", confirm_order,
         name="order-confirm"),
    path("cart/update/<int:pk>/", update_cart,
         name="cart-update"),
    path("cart/remove/<int:pk>/", remove_from_cart,
         name="cart-remove"),
]

app_name = "shop"

templates/layouts/base-fullscreen.html
<!--
=========================================================
* Soft UI Design System - v1.0.1
=========================================================

* Product Page: https://www.creative-tim.com/product/soft-ui-design-system
* Copyright 2021 Creative Tim (https://www.creative-tim.com)

Coded by www.creative-tim.com

 =========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{{ ASSETS_ROOT }}/img/apple-icon.png">
  <link rel="icon" type="image/png" href="{{ ASSETS_ROOT }}/img/favicon.png">
  <link rel="canonical" href="https://appseed.us/ui-kit/soft-ui-design-system"/>
  
  <title>
    Restaurant kitchen - {% block title %}{% endblock %} | AppSeed
  </title>

  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
  <!-- Nucleo Icons -->
  <link href="{{ ASSETS_ROOT }}/css/nucleo-icons.css" rel="stylesheet" />
  <link href="{{ ASSETS_ROOT }}/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <link href="{{ ASSETS_ROOT }}/css/nucleo-svg.css" rel="stylesheet" />
  <!-- CSS Files -->
  <link id="pagestyle" href="{{ ASSETS_ROOT }}/css/soft-design-system.css?v=1.0.1" rel="stylesheet" />
  <link href="{{ ASSETS_ROOT }}/css/style.css" rel="stylesheet" />
  <!-- Specific CSS goes HERE -->
  {% block stylesheets %}{% endblock stylesheets %}

</head>
<body class="{% block body_class %}{% endblock body_class %}">

    {% block content %}{% endblock content %}
  
    {% include "includes/scripts.html" %}

  <!-- Specific JS goes HERE --> 
  {% block javascripts %}{% endblock javascripts %}

</body>
</html>

templates/layouts/base-presentation.html
<!--
=========================================================
* Soft UI Design System - v1.0.1
=========================================================

* Product Page: https://www.creative-tim.com/product/soft-ui-design-system
* Copyright 2021 Creative Tim (https://www.creative-tim.com)

Coded by www.creative-tim.com

 =========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{{ ASSETS_ROOT }}/img/apple-icon.png">
  <link rel="icon" type="image/png" href="{{ ASSETS_ROOT }}/img/favicon.png">
  <link rel="canonical" href="https://appseed.us/ui-kit/soft-ui-design-system"/>
  
  <title>
    Shop - {% block title %}{% endblock %} | AppSeed
  </title>

  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
  <!-- Nucleo Icons -->
  <link href="{{ ASSETS_ROOT }}/css/nucleo-icons.css" rel="stylesheet" />
  <link href="{{ ASSETS_ROOT }}/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <link href="{{ ASSETS_ROOT }}/css/nucleo-svg.css" rel="stylesheet" />
  <!-- CSS Files -->
  <link id="pagestyle" href="{{ ASSETS_ROOT }}/css/soft-design-system.css?v=1.0.1" rel="stylesheet" />
  <link href="{{ ASSETS_ROOT }}/css/style.css" rel="stylesheet" />
  <!-- Specific CSS goes HERE -->
  {% block stylesheets %}{% endblock stylesheets %}

</head>


<script>
  setTimeout(() => {
    document.querySelectorAll('.alert').forEach(alert => {
      alert.classList.remove('show');
      alert.classList.add('fade');
    });
  }, 3000);
</script>


<body class="{% block body_class %}{% endblock body_class %}">

    {% include "includes/navigation.html" %}

    {% if messages %}
      <div class="position-fixed top-0 end-0 p-3" style="z-index: 2000;">
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }} shadow fade show fs-4 px-5 py-4">
              {{ message }}
            </div>
          {% endfor %}
      </div>
    {% endif %}

    {% block content %}{% endblock content %}
    <a href="{% url 'shop:cart-detail' %}" class="btn bg-gradient-primary position-fixed" style="bottom: 20px; right: 20px; z-index: 1050;">
      🛒 Cart
    </a>

    {% block pagination %}
        {% include "includes/pagination.html" %}
    {% endblock %}
  
    {% include "includes/footer.html" %}

    {% include "includes/scripts.html" %}

  <!-- Specific JS goes HERE --> 
  {% block javascripts %}{% endblock javascripts %}

</body>
</html>

templates/layouts/base.html
<!--
=========================================================
* Soft UI Design System - v1.0.1
=========================================================

* Product Page: https://www.creative-tim.com/product/soft-ui-design-system
* Copyright 2021 Creative Tim (https://www.creative-tim.com)

Coded by www.creative-tim.com

 =========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{{ ASSETS_ROOT }}/img/apple-icon.png">
  <link rel="icon" type="image/png" href="{{ ASSETS_ROOT }}/img/favicon.png">
  <link rel="canonical" href="https://appseed.us/ui-kit/soft-ui-design-system"/>
  
  <title>
    Shop - {% block title %}{% endblock %} | AppSeed
  </title>

  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
  <!-- Nucleo Icons -->
  <link href="{{ ASSETS_ROOT }}/css/nucleo-icons.css" rel="stylesheet" />
  <link href="{{ ASSETS_ROOT }}/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <link href="{{ ASSETS_ROOT }}/css/nucleo-svg.css" rel="stylesheet" />
  <!-- CSS Files -->
  <link id="pagestyle" href="{{ ASSETS_ROOT }}/css/soft-design-system.css?v=1.0.1" rel="stylesheet" />
  <link href="{{ ASSETS_ROOT }}/css/style.css" rel="stylesheet" />
  <!-- Specific CSS goes HERE -->
  {% block stylesheets %}{% endblock stylesheets %}

</head>
<body class="{% block body_class %}{% endblock body_class %}">

    {% block content %}{% endblock content %}
  
    {% include "includes/footer.html" %}

    {% include "includes/scripts.html" %}

  <!-- Specific JS goes HERE --> 
  {% block javascripts %}{% endblock javascripts %}

</body>
</html>