accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (
    register_user,
    MyOrderListView,
    ProfileView,
    MyOrderDetailView,
    UserListView, UserDetailView, SupportCreateView, AccountUpdateView
)

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'),
         name='login'),
    path('register/', register_user,
         name='register'),
    path('logout/', LogoutView.as_view(),
         name='logout'),

    path('myorders/', MyOrderListView.as_view(),
         name='myorder-list'),
    path('myorders/<int:pk>/', MyOrderDetailView.as_view(),
         name='myorder-detail'),

    path('profile/', ProfileView.as_view(),
         name='profile'),
    path('users/', UserListView.as_view(),
         name='user-list'),
    path('users/<int:pk>/', UserDetailView.as_view(),
         name='user-detail'),
    path('account/', AccountUpdateView.as_view(),
         name='account-update'),

    path('support/', SupportCreateView.as_view(),
         name='support'),
]

app_name = "accounts"

minishop_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shop.urls", namespace="shop")),
    path("accounts/", include(("accounts.urls", "accounts"), namespace="accounts")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path

from .views import (
    index,
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    OrderListView,
    ProductCategoryListView,
    ProductCategoryDetailView,
    ProductCategoryCreateView,
    ProductCategoryUpdateView,
    ProductCategoryDeleteView,
    add_to_cart,
    cart_detail,
    confirm_order,
    update_cart,
    remove_from_cart,
    OrderDetailView
)

urlpatterns = [
    path('', index, name='index'),
    path('products/', ProductListView.as_view(),
         name='product-list'),
    path('products/<int:pk>/', ProductDetailView.as_view(),
         name='product-detail'),
    path('products/create/', ProductCreateView.as_view(),
         name='product-create'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(),
         name='product-update'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(),
         name='product-delete'),

    path('orders/', OrderListView.as_view(),
         name='order-list'),
    path('orders/<int:pk>/', OrderDetailView.as_view(),
         name='order-detail'),

    path('categories/', ProductCategoryListView.as_view(),
         name='productcategory-list'),
    path('categories/create/', ProductCategoryCreateView.as_view(),
         name='productcategory-create'),
    path('categories/<int:pk>/', ProductCategoryDetailView.as_view(),
         name='productcategory-detail'),
    path('categories/<int:pk>/update/', ProductCategoryUpdateView.as_view(),
         name='productcategory-update'),
    path('categories/<int:pk>/delete/', ProductCategoryDeleteView.as_view(),
         name='productcategory-delete'),

    path("cart/add/<int:pk>/", add_to_cart,
         name="add-to-cart"),
    path("cart/", cart_detail,
         name="cart-detail"),
    path("order/confirm/", confirm_order,
         name="order-confirm"),
    path("cart/update/<int:pk>/", update_cart,
         name="cart-update"),
    path("cart/remove/<int:pk>/", remove_from_cart,
         name="cart-remove"),
]

app_name = "shop"

templates/includes/footer.html
  <footer class="footer pt-5 mt-5">
    <hr class="horizontal dark mb-5">
    <div class="container">
      <div class=" row">
        <div class="col-md-3 mb-4 ms-auto">
          <div>
            <h6 class="text-gradient text-primary font-weight-bolder">Shop Management</h6>
            <p class="text-sm opacity-8">Special store</p>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-gradient text-primary text-sm">Catalog</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'shop:productcategory-list' %}">
                  Categories
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'shop:product-list' %}">
                  Products
                </a>
              </li>
              {% if request.user.is_staff or request.user.is_employee %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'shop:order-list' %}">
                    Orders
                  </a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:myorder-list' %}">
                    My orders
                  </a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <h6 class="text-gradient text-primary text-sm">Account</h6>
          <ul class="flex-column ms-n3 nav">
            {% if user.is_authenticated %}
              {% if request.user.is_staff or request.user.is_employee %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:user-list' %}">Users</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:profile' %}">My account</a>
                </li>
              {% endif %}
            <li class="nav-item">
              <form method="post" action="{% url 'accounts:logout' %}">
                {% csrf_token %}
                <button type="submit" class="nav-link btn btn-link">Logout</button>
              </form>
            </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">
                  Login
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:register' %}">
                  Register
                </a>
              </li>
            {% endif %}
          </ul>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-gradient text-primary text-sm">Support</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:support' %}">
                  Contact Us
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4 me-auto">
          <div>
            <h6 class="text-gradient text-primary text-sm">Legal</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <span class="nav-link text-muted">
                  2025 Shop Project
                </span>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-12">
          <div class="text-center">
            <p class="my-4 text-sm">
              Built with Django
              - Coded by Me
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/includes/navigation-auth.html
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-sm-3" 
               href="/" rel="tooltip" data-placement="bottom">
              Shop
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2" 
                     href="{% url 'accounts:support' %}">
                    <i class="fa fa-rocket me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Get Free Support">Support</p>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/pagination.html
{% if is_paginated %}
  <form method="get" class="d-flex justify-content-center">
    <ul class="pagination pagination-lg mb-0">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">&laquo;&laquo;</a>
        </li>
      {% endif %}
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
        </li>
      {% endif %}
      <li class="page-item active">
        <span class="page-link">{{ page_obj.number }}</span>
      </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
        </li>
      {% endif %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ paginator.num_pages }}">&raquo;&raquo;</a>
        </li>
      {% endif %}
      <li>
        <input type="number" name="page" min="1" max="{{ paginator.num_pages }}" class="form-control" style="width: 85px;" placeholder="Page" required>
      </li>
      <li>
        <button type="submit" class="btn btn-primary">Go</button>
      </li>
    </ul>
  </form>
{% endif %}

templates/includes/scripts.html
  <script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>